version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 20